# Generated by Django 4.2.6 on 2024-02-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_data', models.TextField()),
                ('qno', models.IntegerField()),
                ('q', models.IntegerField()),
            ],
        ),
    ]
