# Generated by Django 4.2.6 on 2024-02-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitteddata',
            name='q',
        ),
    ]
